services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=c4X1BtFHi60rON
      - POSTGRES_DB=dnsbin
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  dnsbin:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "53:53"
      - "53:53/udp"
    environment:
      - DB_SOURCE=postgresql://root:c4X1BtFHi60rON@postgres:5432/dnsbin?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./wait-for.sh", "postgres:5432", "--", "./start.sh", "./main"]
    
volumes:
  data-volume: